// <auto-generated />
namespace ControleDApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialformysql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialformysql));
        
        string IMigrationMetadata.Id
        {
            get { return "202005291231330_initial-for-mysql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
